### PR TITLE
Added alternative Nunchuck identifier

### PR DESCRIPTION
**Pull request by SaffronCR**
There's some nunchucks with a different id. This change would support both models.

### CODE REVIEW

**Comment by Flafla2** [comment]
Is this behavior documented anywhere?  I am assuming the nunchuck you are referring to is third-party, can you confirm?

**Comment by SaffronCR** [comment]
It's from a official nunchuck, I know it exists because I have one here that came with my Wii.
I've tried googling it and looks like other projects also have it listed, e.g.:

https://github.com/simphax/WiimoteLib/blob/master/WiimoteCS/WiimoteLib/DataTypes.cs

Has listed two nunchucks:
Nunchuk = 0x0000a4200000,
NewNunchuk = 0xff00a4200000,

**Comment by Flafla2** [comment]
Interesting - Wiibrew (my primary resource) doesn't document this.  It seems like a valid problem though, so I'll approve the request.

**Comment by SaffronCR** [comment]
Yeah, Wiibrew has some missing pieces.

Thanks and good work! This plugin has helped me a lot ;)

**Pull request merged**
