### PR TITLE
speaker support (fixes #48)

### LINKED ISSUE #48: Speaker support
Hello, 
Very interesting project!
I saw you had speaker support on the roadmap, I thought I can open an issue to discuss it a bit.
Fortunately, writing audio data looks straight forward according to 
http://wiibrew.org/wiki/Wiimote#Speaker
It is just writing a 0x18 report to send the data. More precisely, the sequence to enable the speaker is

```
Enable speaker (Send 0x04 to Output Report 0x14)
Mute speaker (Send 0x04 to Output Report 0x19)
Write 0x01 to register 0xa20009
Write 0x08 to register 0xa20001
Write 7-byte configuration to registers 0xa20001-0xa20008
Write 0x01 to register 0xa20008
Unmute speaker (Send 0x00 to Output Report 0x19)

```
And right after, it is writing the data with 0x18 reports.
The format seems to be documented enough, And also I found the dolphin emulator to be pretty inspiring.
It seems that also another challenge is to send these 20 bytes chunks at small and precise intervals.

So, a high level api could be getting the data from a Unity audio clip, but under the hood it's reading the content, resampling it, and sending it off to the remote.

I'm I missing anything else?
PS: I have no wiimote to test with whatsoever, but I will investigate this once I get hold of one.
Cheers

### PR DESCRIPTION
**Pull request by iBicha**
#48 follow up:
This is an initial test for speaker support. Please do not merge yet for the following reasons : 

- Audio format is hard coded to mono/8bits/2000hz. The plugin will need a resampling function that can convert any PCM format to the optimal one for the speaker
- The quality is very jittery, slow and bad. But at least I can hear something, and it feels like the audio clip used
- The example scene is saved using Unity 2017 (while the project is running 5.3 I think?)

Anyway, I'm probably doing something wrong somewhere, either passing the config to the registers correctly, or it's the bad format i'm using. following http://wiibrew.org/wiki/Wiimote#Speaker_Configuration things feels right so far.

Side note, since there is a `Wiimote.Speaker` field now, I don't think there is a need for the `SendSpeakerEnabled` and `SendSpeakerMuted`. We can probably remove them; since I doubt anyone is using them in their project (why would anyone call mute when the speaker is not yet supported)

### CODE REVIEW

**Comment by iBicha** [comment]
Another matter to review is, resampling audio. NAudio sounds like a good candidate for resampling, but it felt overpowered for this purpose. It's too big to include just to downsample the audio. Maybe a simple implementation of signal resampling would be enough.

**Comment by iBicha** [comment]
PS: I don't have access to a wiimote, at least not anytime soon, I might not be able to finish this feature.

**Comment by iBicha** [comment]
Closing for inactivity

**Comment by Trihy** [comment]
Did you tried with a non TR wiimote? Non TR will never have proper sound because of some HW limitations with BT. TR ones are good. Didnt tried this plugin/commit but it´s possible to play proper audio on TR ones.

It´s already docummented here how to get proper sound /trigger-segfault/WiimoteLib.Net

**Pull request closed without merging**
